### ISSUE TITLE
Public S3 bucket

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/planning-entitlements#7]
Supposedly the city-planning-entitlements bucket is public. Jonathan can't open it from his JupyterHub. Do we need to ask for AWS credentials, or is there a way around it?

**Comment by ian-r-rose** [comment]
This is unfortunately a bit tricky. GDAL fails reading from s3 by default if no AWS credentials are found, even if the bucket and objects in it are public. I think this is a pretty bad UX, cf. https://trac.osgeo.org/gdal/ticket/7205

There are three ways forward, as far as I can tell.
1. Set the environment variable `AWS_NO_SIGN_REQUEST=YES`, in our analysis notebook, which allows for anonymous access. This is the quickest fix to this problem.
2. Set the environment variable `AWS_NO_SIGN_REQUEST=YES` in `intake_geopandas`/`fiona`. Requires upstreaming, and may not be the best place for the fix.
3. Optionally use the public URL instead of the `s3` URI when creating the open data catalog in the `mirror` subcommand for `intake-dcat`. Would require adding this as an option to `intake-dcat`.

**Comment by hunterowens** [comment]
Alternatively, we can setup S3 credentials for @jonlchiu?

**Comment by ian-r-rose** [comment]
Yep, that is also an option. Probably need to do that anyways, since there may be some non-public data.

**Comment by hunterowens** [comment]
Yeah, with PCTS, I think we should open a ticket.

**Comment by ian-r-rose** [comment]
@phammichelle has opened a ticket for this.

**Comment by hunterowens** [comment]
@ian-r-rose did @jonlchiu get setup with S3?

**Comment by ian-r-rose** [comment]
We have gotten him access and API tokens, but we haven't onboarded him with them yet.

**Comment by hunterowens** [comment]
Let's close this and open an issue for onboarding him plus new DA once
hired

**Comment by tiffanychu90** [comment]
Today we went to onboard him, and realized cloud team only gave him console access, but not tokens we need. Opened new SNow ticket for this.

**Comment by tiffanychu90** [comment]
Closing because @trantom has access to S3.
